server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  # Shut off the client functionality of the Eureka server (used for HA)
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
